import os
import json
import gzip

with open('pubmed_listing.txt') as f:
	allpubmedfilenames = [ line.strip() for line in f ]
	allpubmedfilenames = [ os.path.basename(fn) for fn in allpubmedfilenames ]
	allpubmedfilenames = [ re.sub(r'\.gz$','',fn) for fn in allpubmedfilenames ]

with gzip.open('../last_release/process_record.json.gz','rt') as f:
	processedfilenames = json.load(f)['pubmed_files']
	
print(sorted(processedfilenames)[-1])
	
pubmed_to_process = [ f for f in allpubmedfilenames if not f in processedfilenames ]

pubmed_to_process = sorted(pubmed_to_process)
pubmed_to_process = [ os.path.join('pubmed_corona',fn) for fn in pubmed_to_process ]

rule:
	input: pubmed_to_process

rule:
	output: "pubmed_corona/{filename}"
	shell: "bash downloadAndProcessPubmedFile.sh {wildcards.filename} {output}"

