import os

with open('pubmed_listing.txt') as f:
	filenames = [ line.strip() for line in f ]
	filenames = [ os.path.basename(fn) for fn in filenames ]
	filenames = [ re.sub(r'\.gz$','',fn) for fn in filenames ]
	filenames = [ os.path.join('pubmed_corona',fn) for fn in filenames ]
	filenames = sorted(filenames)

rule:
	input: filenames

rule:
	output: "pubmed_corona/{filename}"
	shell: "bash downloadAndProcessPubmedFile.sh {wildcards.filename} {output}"

