import os

with open('pubmed_listing.txt') as f:
	allpubmedfilenames = [ line.strip() for line in f ]

with open('pubmed_listing_alreadyprocessed.txt') as f:
	processedfilenames = [ line.strip() for line in f ]
	
pubmed_to_process = [ f for f in allpubmedfilenames if not f in processedfilenames ]
pubmed_to_process = [ os.path.basename(fn) for fn in pubmed_to_process ]
pubmed_to_process = [ re.sub(r'\.gz$','',fn) for fn in pubmed_to_process ]
pubmed_to_process = [ os.path.join('pubmed_corona',fn) for fn in pubmed_to_process ]
pubmed_to_process = sorted(pubmed_to_process)

rule:
	input: pubmed_to_process

rule:
	output: "pubmed_corona/{filename}"
	shell: "bash downloadAndProcessPubmedFile.sh {wildcards.filename} {output}"

