name: Pipeline Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-transformer
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.cache/torch/transformers/
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
        python -m nltk.downloader stopwords
    - name: Setup and run full pipeline with a tiny dataset
      run: |
        sh run_test.sh

