import json

with open('parameterSpace.json') as f:
	parameterSpaceSize = len(json.load(f))

rule:
	input: [ "results/%d.txt" % i for i in range(parameterSpaceSize) ]

rule:
	output: "results/{index}.txt"
	shell: "python crossvalidate.py --documents ../pipeline/data/alldocuments.withannotations.json --parameterSpace parameterSpace.json --parameterIndex {wildcards.index} > {output}"

